/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package univs.edu.telasInstituicao;

import javax.swing.JOptionPane;
import univs.edu.instituicao.Instituicao;
import univs.edu.instituicao.InstituicaoDAO;

/**
 *
 * @author Lucas007
 */
public class EditarInstituicao extends javax.swing.JFrame {

    Instituicao instituicao = new Instituicao();
    InstituicaoDAO dao = new InstituicaoDAO();

    public void atualizarCampos() {
        instituicao = Instituicao.instituicao;
        tfEditarEmailInstituicao.setText(instituicao.getEmail());
        tfEditarNomeInstituicao.setText(instituicao.getNomeInstituicao());
        tfEditarSenhaInstituicao.setText(instituicao.getSenha());
        tfEditarCidadeInstituicao.setText(instituicao.getCidadeInstituicao());
        tfEditarRuaInstituicao.setText(instituicao.getRuaInstituicao());
        tfEditarTelefone.setText(instituicao.getTelefone());
        tfEditarCnpj.setText(instituicao.getCnpj());
        tfEditarCarteira.setBorderPaintedFlat(instituicao.isCarteira());
        tfEditarCpf.setBorderPaintedFlat(instituicao.isCpf());
        tfEditarTitulo.setBorderPaintedFlat(instituicao.isTitulo());
        tfEditarIdentidade.setBorderPaintedFlat(instituicao.isIdentidade());
    }

    public EditarInstituicao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        tfEditarRuaInstituicao = new javax.swing.JTextField();
        tfEditarNomeInstituicao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfEditarEmailInstituicao = new javax.swing.JTextField();
        tfEditarTelefone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfEditarSenhaInstituicao = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfEditarCidadeInstituicao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfEditarCnpj = new javax.swing.JTextField();
        tfEditarCpf = new javax.swing.JCheckBox();
        tfEditarIdentidade = new javax.swing.JCheckBox();
        tfEditarCarteira = new javax.swing.JCheckBox();
        tfEditarTitulo = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nome.:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        getContentPane().add(tfEditarRuaInstituicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 150, 30));

        tfEditarNomeInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEditarNomeInstituicaoActionPerformed(evt);
            }
        });
        getContentPane().add(tfEditarNomeInstituicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 220, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Senha.:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Rua.:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        tfEditarEmailInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEditarEmailInstituicaoActionPerformed(evt);
            }
        });
        getContentPane().add(tfEditarEmailInstituicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 220, 30));

        tfEditarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEditarTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(tfEditarTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 220, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email.:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        getContentPane().add(tfEditarSenhaInstituicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 220, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cidade.:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Telefone.:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        getContentPane().add(tfEditarCidadeInstituicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 150, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Altere suas Informações");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, 30));

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CNPJ.:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        getContentPane().add(tfEditarCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 30));

        tfEditarCpf.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        tfEditarCpf.setForeground(new java.awt.Color(255, 255, 255));
        tfEditarCpf.setText("CPF");
        getContentPane().add(tfEditarCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 140, -1));

        tfEditarIdentidade.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        tfEditarIdentidade.setForeground(new java.awt.Color(255, 255, 255));
        tfEditarIdentidade.setText("Identidade");
        getContentPane().add(tfEditarIdentidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 140, -1));

        tfEditarCarteira.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        tfEditarCarteira.setForeground(new java.awt.Color(255, 255, 255));
        tfEditarCarteira.setText("Carteira de Trabalho");
        getContentPane().add(tfEditarCarteira, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 140, -1));

        tfEditarTitulo.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        tfEditarTitulo.setForeground(new java.awt.Color(255, 255, 255));
        tfEditarTitulo.setText("Título de Eleitor");
        getContentPane().add(tfEditarTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 140, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Documentos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\GGrio\\OneDrive\\Imagens\\Saved Pictures\\BackgroundEditarEmpresa.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 580, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfEditarNomeInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEditarNomeInstituicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEditarNomeInstituicaoActionPerformed

    private void tfEditarEmailInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEditarEmailInstituicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEditarEmailInstituicaoActionPerformed

    private void tfEditarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEditarTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEditarTelefoneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ConfigInstituicao config = new ConfigInstituicao();
        config.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (tfEditarEmailInstituicao.getText().isEmpty() || tfEditarNomeInstituicao.getText().isEmpty()
                || tfEditarCidadeInstituicao.getText().isEmpty() || tfEditarRuaInstituicao.getText().isEmpty() || tfEditarSenhaInstituicao.getText().isEmpty()
                || tfEditarTelefone.getText().isEmpty() || tfEditarCnpj.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os Campos");

        } else {
            instituicao.setEmail(tfEditarEmailInstituicao.getText());
            instituicao.setCidadeInstituicao(tfEditarCidadeInstituicao.getText());
            instituicao.setNomeInstituicao(tfEditarNomeInstituicao.getText());
            instituicao.setRuaInstituicao(tfEditarRuaInstituicao.getText());
            instituicao.setSenha(tfEditarSenhaInstituicao.getText());
            instituicao.setTelefone(tfEditarTelefone.getText());
            instituicao.setCnpj(tfEditarCnpj.getText());
            instituicao.setCpf(tfEditarCpf.isSelected());
            instituicao.setCarteira(tfEditarCarteira.isSelected());
            instituicao.setTitulo(tfEditarTitulo.isSelected());
            instituicao.setIdentidade(tfEditarIdentidade.isSelected());
            dao.salvar(instituicao);

            ConfigInstituicao config = new ConfigInstituicao();
            config.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarInstituicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JCheckBox tfEditarCarteira;
    private javax.swing.JTextField tfEditarCidadeInstituicao;
    private javax.swing.JTextField tfEditarCnpj;
    private javax.swing.JCheckBox tfEditarCpf;
    private javax.swing.JTextField tfEditarEmailInstituicao;
    private javax.swing.JCheckBox tfEditarIdentidade;
    private javax.swing.JTextField tfEditarNomeInstituicao;
    private javax.swing.JTextField tfEditarRuaInstituicao;
    private javax.swing.JPasswordField tfEditarSenhaInstituicao;
    private javax.swing.JTextField tfEditarTelefone;
    private javax.swing.JCheckBox tfEditarTitulo;
    // End of variables declaration//GEN-END:variables
}
